import { RESOURCES, type Category } from "../../resources";

const categories: Array<{
  key: Category;
  icon: string;
  label: string;
  description: string;
}> = [
  { key: "housing", icon: "🏠", label: "Housing", description: "Eviction, rent, landlord" },
  { key: "healthcare", icon: "🏥", label: "Healthcare", description: "Medical bills, insurance" },
  { key: "benefits", icon: "🍎", label: "Food & benefits", description: "SNAP, food stamps" },
  { key: "utilities", icon: "⚡", label: "Utilities", description: "Shutoff notice" },
  { key: "legal", icon: "⚖️", label: "Legal trouble", description: "Court, fines, summons" },
  { key: "school", icon: "🎓", label: "School", description: "Financial aid, forms" },
  { key: "financial", icon: "💳", label: "Debt & money", description: "Collections, bills" },
  { key: "immigration", icon: "🛂", label: "Immigration", description: "USCIS, visas" },
  { key: "other", icon: "🤝", label: "Something else", description: "General resources" },
];

const categoryTitles: Record<Category, string> = {
  housing: "🏠 Housing help",
  healthcare: "🏥 Healthcare help",
  benefits: "🍎 Food & benefits",
  utilities: "⚡ Utility help",
  legal: "⚖️ Legal help",
  school: "🎓 School & financial aid",
  financial: "💳 Debt & money help",
  immigration: "🛂 Immigration help",
  other: "🤝 General resources",
};

export function LetterHelpScreen({
  category,
  onBack,
  onChooseCategory,
  onOpenLetter,
}: {
  category: Category | null;
  onBack: () => void;
  onChooseCategory: (category: Category | null) => void;
  onOpenLetter: () => void;
}) {
  return (
    <div className="mx-auto max-w-5xl py-10">
      <button className="mb-6 min-h-11 rounded-lg text-sm font-bold text-muted hover:text-ink focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-amber" onClick={onBack} type="button">
        ← Back
      </button>

      {!category ? (
        <>
          <p className="lantern-eyebrow">Verified help</p>
          <h1 className="mt-3 font-serif text-4xl tracking-[-0.04em] text-ink sm:text-5xl">What&apos;s going on?</h1>
          <p className="mt-3 max-w-2xl text-sm leading-6 text-muted">
            Pick the closest option. Lantern will show hand-checked national resources without requiring a letter.
          </p>
          <div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3">
            {categories.map((item) => (
              <button
                className="flex min-h-36 flex-col items-start gap-3 rounded-card border border-ink/10 bg-surface p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-cobalt/35 hover:shadow-md focus-visible:outline-3 focus-visible:outline-offset-3 focus-visible:outline-amber"
                key={item.key}
                onClick={() => onChooseCategory(item.key)}
                type="button"
              >
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#eef2ff] text-xl">{item.icon}</span>
                <span>
                  <span className="block text-sm font-bold text-ink">{item.label}</span>
                  <span className="mt-0.5 block text-xs text-muted">{item.description}</span>
                </span>
              </button>
            ))}
          </div>
          <div className="mt-6 rounded-feature border border-cobalt/20 bg-[#eef2ff] p-5 text-center">
            <p className="font-bold text-ink">Not sure? Call 211</p>
            <p className="mt-1 text-sm text-[#53628b]">Free, confidential, available around the clock, and offered in many languages.</p>
            <a className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-cobalt px-4 text-sm font-bold text-white" href="tel:211">Call 211</a>
          </div>
          <p className="mt-5 text-center text-sm text-muted">
            Or <button className="font-bold text-cobalt underline decoration-cobalt/30 underline-offset-4" onClick={onOpenLetter} type="button">upload a letter</button> and Lantern will explain it.
          </p>
        </>
      ) : (
        <>
          <button className="mb-5 min-h-11 rounded-lg text-sm font-bold text-cobalt focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-amber" onClick={() => onChooseCategory(null)} type="button">
            ← All categories
          </button>
          <h1 className="font-serif text-4xl tracking-[-0.04em] text-ink">{categoryTitles[category]}</h1>
          <p className="mt-3 text-sm text-muted">Real, free, national resources verified by hand—not generated by AI.</p>
          <div className="mt-6 grid gap-3 md:grid-cols-2">
            {RESOURCES[category].map((resource) => (
              <article className="rounded-card border border-ink/10 bg-surface p-5 shadow-sm" key={resource.name}>
                <h2 className="font-bold text-ink">{resource.name}</h2>
                <p className="mt-1 text-sm leading-6 text-muted">{resource.desc}</p>
                <div className="mt-4 flex flex-wrap gap-2">
                  {resource.phone ? <a className="inline-flex min-h-11 items-center rounded-xl bg-cobalt px-4 text-sm font-bold text-white" href={`tel:${resource.phone}`}>Call {resource.phone}</a> : null}
                  {resource.url ? <a className="inline-flex min-h-11 items-center rounded-xl border border-ink/15 bg-white px-4 text-sm font-bold text-ink" href={resource.url} rel="noopener noreferrer" target="_blank">Visit website ↗</a> : null}
                </div>
              </article>
            ))}
          </div>
          <div className="mt-6 rounded-feature border border-ink/10 bg-surface p-5 text-center shadow-sm">
            <p className="font-bold text-ink">Have a letter about this?</p>
            <p className="mt-1 text-sm text-muted">Upload it to see what it says and what to do next.</p>
            <button className="mt-4 min-h-11 rounded-xl bg-cobalt px-4 text-sm font-bold text-white" onClick={onOpenLetter} type="button">Upload my letter</button>
          </div>
        </>
      )}
    </div>
  );
}
